# Site identity
title: InfernoDroid
tagline: Powered by flame. Built by curiosity.
description: >
  InfernoDroid is a community-driven hub for experiments,
  creative projects, and chaotic ideas â€” built in public.

url: "https://infernodroid.github.io"
baseurl: "/website"

# Branding
logo: /assets/images/inferix-normal.png

# Markdown / build
markdown: kramdown
highlighter: rouge

# Theme
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Exclude unnecessary files
exclude:
  - node_modules
  - .github
  - README.md
